[package]
name = "cross-windows"
version = "0.1.0"
edition = "2018"

[dependencies]
# This example uses Serde to prove that Naersk works correctly even when some of
# the dependencies have build scripts:
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
