name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  install-nix:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: './.github/actions/nix'
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test'
