name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  linux:
    strategy:
        matrix:
            nixpkgs: [ nixpkgs, nixpkgs-21.05, nixpkgs-22.05, nixpkgs-23.05 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Run tests"
        run: './script/test --nixpkgs "$nixpkgs"'
        env:
            nixpkgs: ${{ matrix.nixpkgs }}
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Run tests"
        run: './script/test'
