name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  linux:
    strategy:
        matrix:
            nixpkgs: [ nixpkgs, nixpkgs-21.05, nixpkgs-21.11 ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test --nixpkgs "$nixpkgs" '
        env:
            nixpkgs: ${{ matrix.nixpkgs }}
  darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test'
