name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  install-nix:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: './.github/actions/nix'
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test'
