name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  install-nix:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: naersk
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test'
