name: "test"
on:
  push:
    branches:
      - 'master'

jobs:
  linux:
    strategy:
        matrix:
            nixpkgs: [ nixpkgs, nixpkgs-21.05, nixpkgs-22.05, nixpkgs-23.05 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test --nixpkgs "$nixpkgs" '
        env:
            nixpkgs: ${{ matrix.nixpkgs }}
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: "Run tests"
        run: './script/test'
